@startuml
(*) --> "ルーティングポリシーと各レコードに指定した値に基づいてレコードを選択する"
--> "レコードが正常かどうかを決定する"
--> ===B1===
--> "関連付けられたヘルスチェックを持つ非エイリアスレコード"
--> ===B2===
===B1=== --> "[Evaluate Target Health (ターゲットの正常性の評価)] が [Yes (あり)] に設定されたエイリアスレコード"
--> ===B2===
--> if レコードが正常 then
    --> [YES] "そのレコードから得た値 (IP アドレスなど) でクエリに応答する"
    else
    --> [NO] "同じ基準で別のレコードを選択し、正常なレコードが見つかるまでそのプロセスを繰り返します"
@enduml
